import argparse

def add_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--vid_num', default=1000, type=int)
    parser.add_argument('--id_num', default=10, type=int)
    parser.add_argument('--dataset', default='own')
    parser.add_argument('--s1_thre', default=10, type=int)
    parser.add_argument('--s2_thre', default=10, type=int)
    parser.add_argument('--oversampling', default=False, action='store_true')
    # parser.add_argument('--do_s1', default=False, action='store_true')
    # parser.add_argument('--do_s2', default=False, action='store_true')
    parser.add_argument('--ext_mode', default=1,
    help='select the extract mode for id, 0 means that don\'t extract it, 1 means that extract from the beginning, 2 means that extract before the MLP stage, 3 means that extract mix method, 4 means that only use aggressive clip to train', type=int)
    parser.add_argument('--gap', default=1, type=int, help='get MOT gap, when train data is frame by frame')
    parser.add_argument('--test', default=False, action='store_true')
    parser.add_argument('--load', default=False, action='store_true')
    parser.add_argument('--neighber', default=6, type=int)
    parser.add_argument('--half1', default=False, action='store_true')
    parser.add_argument('--half2', default=False, action='store_true')
    parser.add_argument('--cmp', default=False, action='store_true')
    parser.add_argument('--old', default=False, action='store_true')
    parser.add_argument('--ml', default=False, action='store_true')
    parser.add_argument('--dl', default=False, action='store_true')
    parser.add_argument('--original', default=False, action='store_true')
    parser.add_argument('--anomaly', default=False, action='store_true')
    parser.add_argument('--visualize', default=False, action='store_true')
    # DL model config setting
    parser.add_argument('--batch_size', default=8)
    parser.add_argument('--worker', default=1)
    parser.add_argument('--epochs', default=100)
    parser.add_argument('--train_log', default=100)
    parser.add_argument('--lr', default=0.00001)
    parser.add_argument('--focal_loss', default=False, action='store_true')
    return parser.parse_args() 
